# review-epubmaker向けの設定ファイルの例。
# yamlファイルをRe:VIEWファイルのある場所に置き、
# 「review-epubmaker yamlファイル」を実行すると、<bookname>.epubファイルが
# 生成されます。
# このファイルはUTF-8エンコーディングで記述してください。

# ブック名(ファイル名になるもの。ASCII範囲の文字を使用)
bookname: the-androidstudio-book
# 書名
booktitle: 「Android Studioで始める 簡単Androidアプリ開発」 補足資料
# 著者
aut: 有山 圭二
ill: 根雪れい
prt: blog.keiji.io
prt_url:  https://github.com/keiji/the-androidstudio-book
#edt: 有山圭二
date: コミックマーケット87
rights: |
  本書の内容は、有山圭二の著作物です。また、本書の表紙及び裏表紙のイラストは根雪れいの著作物です。
  本書の全部、または一部について、著作者から文書による許諾を得ずに複製することは禁じられています。
description:
# 以下はオプション
# asn: Associated name
# ant: Bibliographic antecedent
# clb: 貢献者
# edt: 編集者
# dsr: デザイナ
# pht: 撮影者
# trl: 翻訳者
# description: ブックの説明
#
# coverfile: カバーページのbody要素内に挿入する内容を記述したファイル名
#coverfile: _cover.html
# coverimage: 表紙用画像ファイル
#coverimage: cover.jpg
# 固有IDに使用するドメイン
urnid: http://gihyo.jp/book/2014/978-4-7741-6998-9

texdocumentclass: ["jsbook", "b5j,twoside,openany"]

# CSSファイル (yamlファイルおよびRe:VIEWファイルを置いたディレクトリにあること
stylesheet: style.css
# 目次として抽出するレベル
toclevel: 2
# セクション番号を表示するレベル
secnolevel: 3
# review-compileに渡すパラメータ
params: --stylesheet=style.css
# 目次生成用？
mytoc: true
# 奥付生成用
colophon: true
texstyle: reviewmacro
pubhistory: |
  Android Studio 1.0 対応版
debug: false
